### PR TITLE
Fix for lifeline selector issue

### LINKED ISSUE #97: Ember Lifeline No Longer Supports jQuery selectors
I just updated ember-light-table to 1.12.2 (from 1.8.6), which bumped `ember-lifeline.`

Ember-Lifeline stops supporting jquery selectors here https://github.com/rwjblue/ember-lifeline/blob/master/addon/mixins/dom.js, resulting in: `Called addEventListener with selector not found in DOM [Object: Object]`

PR forthcoming.

### PR DESCRIPTION
**Pull request by donaldwasserman**
Fixes #97

### CODE REVIEW

**Comment by alexander-alvarez** [comment]
should we bump lifeline also here: https://github.com/offirgolan/ember-burger-menu/blob/master/package.json#L68 ?

**Comment by offirgolan** [comment]
@donaldwasserman thank you for this. Can you bump up ember-lifeline where @alexander-alvarez pointed at?

**Comment by donaldwasserman** [comment]
@offirgolan All set!

**Comment by donaldwasserman** [comment]
Ok. the tests not at least pass on my machine.

**Comment by offirgolan** [comment]
Awesome! Thank you @donaldwasserman 😄

**Comment by offirgolan** [comment]
Released with `v3.0.1`.

**Pull request merged**
