### PR TITLE
fix(element-closest): IE11 fix to use implementation via npm package `element-closest`

### LINKED ISSUE #115: Win-IE11: console errors breaking application
Ran into a problem after I updated my application from [v3.1.0](https://github.com/offirgolan/ember-burger-menu/releases/tag/v3.1.0) to [v3.3.1](https://github.com/offirgolan/ember-burger-menu/releases/tag/v3.3.1) and then testing on IE11. When I did this, I first noticed there were certain parts of the app that didn't fully load and click event handlers were not working.

Digging into the console errors - Found that this is the PR causing the issue https://github.com/offirgolan/ember-burger-menu/pull/109 - It's triggering console errors now `Invalid Calling Object`

:heart: removing jQuery but would still love the continued IE11 support here as it worked previously.

Some screenshots just running the demo page in a VM:

Narrowed the issue down to here when it's executing [`matchesFn(selector)`](https://github.com/offirgolan/ember-burger-menu/blob/v3.3.1/addon/utils/element-closest.js#L19)

### PR DESCRIPTION
**Pull request by alexdiliberto**
This should Fix #115 

Ran the dummy app on the same IE11 VM and it now works, let me know what you think about the implementation. I opted to just use something battletested instead of a custom util...it feels like this `element-closest` package does the trick and fully works cross-browser. Also plucked the `this.import()` polyfill from [an `ember-simple-auth` implementation](https://github.com/simplabs/ember-simple-auth/blob/master/index.js#L36-L50) which seems very stable

### CODE REVIEW

**Comment by offirgolan** [comment]
@alexdiliberto thanks for taking the time to look into this. As discussed in #109, I'd rather not force the Element.closest method/polyfill since it will be added to the host app and could cause unforeseen implications. 

I think we can use something like [closest](https://www.npmjs.com/package/closest) with [ember-auto-import](https://github.com/ef4/ember-auto-import) instead.

**Comment by alexdiliberto** [comment]
@offirgolan Yea great suggestion, I just pushed up a quick update to implement your above comments. Let me know if this conforms to expected behavior. Thanks 👍

**Comment by offirgolan** [comment]
Looks great. Can you confirm that this works for you in the IE11 VM?

**Comment by alexdiliberto** [comment]
Yup 👍 demo app works as expected when launching through IE11 VM and no more console errors

**Comment by offirgolan** [comment]
Released with `v3.3.2`. Thanks again @alexdiliberto!

**Pull request merged**
