### PR TITLE
[WIP] Updates

### PR DESCRIPTION
**Pull request by mwisner**
This PR upgrades all dependencies to their latest versions. 

TODO:
-- Replace jshint with eslint
-- Wait for upstream fix for (https://github.com/emberjs/ember.js/issues/15621) or come up with work around. Currently menu items are not rendered in the demo as a result.

### CODE REVIEW

**Comment by offirgolan** [comment]
@mwisner this is awesome! Thank you for taking the time to do this 😸

**Comment by mwisner** [comment]
@offirgolan my pleasure! Would you prefer me to wait until the partial issues are fixed in ember or try and work out a refactor that doesn't use partials? 

I know that in ember slack generally speaking it seems people frown upon using partials, but at the same time in the demo app it seems like a valid use case at least to me...

**Comment by offirgolan** [comment]
@mwisner totally up to you. If you want to get this in asap, then you can just convert the partial to a component.

**Comment by offirgolan** [comment]
Closing in favor of #100

**Pull request closed without merging**
