### PR TITLE
Fastboot

### PR DESCRIPTION
**Pull request by mayko780**
Fixed some fastboot issues.

### CODE REVIEW

**Comment by offirgolan** [comment]
@mayko780 is there a better way to check if the app is in fastboot mode? Does it expose some environment variable of sort?

**Comment by mayko780** [comment]
There is the fastboot service, but this blow the code a little. 
http://ember-fastboot.com/docs/addon-author-guide#accessing-the-fastboot-service

**Comment by offirgolan** [comment]
Damn that sucks...

I think the service is our best bet since thats the correct path to go under. I can make those changes.

**Comment by mayko780** [comment]
You are probably right but, the other code examples in the docs are also using self.document to check if the code is served by node or not.

**Comment by offirgolan** [comment]
@mayko780 can you point me to those examples?

**Comment by mayko780** [comment]
https://github.com/cibernox/ember-basic-dropdown/pull/42/files

**Comment by offirgolan** [comment]
Sweet! Thanks for the follow up 😄

**Comment by mayko780** [comment]
No worries.

**Comment by offirgolan** [comment]
@mayko780 Released with `v2.0.1`.

**Pull request merged**
